# Generated by Django 4.2.1 on 2023-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_feed_like_count_remove_feed_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
